name: Bug Report
description: Report a bug in Starbidz SDK
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Dashboard
        - Bid Server
        - Android SDK (Core)
        - Android SDK (MAX)
        - Android SDK (AdMob)
        - Android SDK (LevelPlay)
        - iOS SDK (Core)
        - iOS SDK (MAX)
        - iOS SDK (AdMob)
        - iOS SDK (LevelPlay)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - SDK Version: x.x.x
        - Platform: Android/iOS
        - OS Version:
        - Device:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help diagnose the problem
      render: shell
