name: Feature Request
description: Suggest a new feature for Starbidz SDK
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this relate to?
      options:
        - Dashboard
        - Bid Server
        - Android SDK
        - iOS SDK
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
